// GENERATED by gen-types.mjs from Sideload/Script/DomApi.cs, Sideload/Script/Bridge.cs and
// Sideload/Script/ScriptHost.cs. Do not edit; run the generator.
//
// Everything a Sideload page can reach, and nothing else. `document` here is NOT the browser's document and
// `SideloadElement` is NOT an `Element`: they are the C# wrappers the engine hands to Jint, and the members below
// are all of them. That is the point of the file. `document.head` and `el.closest('.card')` compile perfectly
// against the DOM lib and then do nothing whatsoever in the game, with no error on either side.
//
// So compile against this WITHOUT the DOM lib - "lib": ["ES2020"], no @types/node. With lib.dom loaded, `window`,
// `localStorage`, `navigator`, `requestAnimationFrame` and `getComputedStyle` all typecheck again, and every one
// of them is undefined at runtime.
//
// A `| null` return is read out of the C# body rather than assumed either way. `_host.Wrap(x)` answers null when x
// does, and AngleSharp's `getAttribute` does the same for an attribute that is not set, so those members say so and
// the doc on each says when. `querySelectorAll` and `children` hand back an empty array instead and are not null.
//
// `Promise` is the one global not declared here: it is Jint's own builtin, so the ES lib already has it.
//
// Members appear in their camelCase spelling only. Jint runs with BothCasings, so the PascalCase C# name works at
// runtime too - but a page should be written in one of the two, and declaring both doubles every completion list.

/** The global `document`. Not the browser's - these six members are all of it. */
interface SideloadDocument {
  readonly body: SideloadElement;

  /** Null when no element on the page carries that id. */
  getElementById(id: string): SideloadElement | null;

  /** Null when nothing on the page matches the selector. */
  querySelector(selector: string): SideloadElement | null;
  querySelectorAll(selector: string): SideloadElement[];
  createElement(tag: string): SideloadElement;
  addEventListener(type: string, handler: (event: SideloadEvent) => void): void;
}

/** One element in the page. Not a browser `Element` - these members are all of it. */
interface SideloadElement {
  readonly tagName: string;
  id: string;
  className: string;
  readonly classList: SideloadClassList;
  readonly style: SideloadStyle;
  textContent: string;
  innerHTML: string;

  /**
   * Form-control value. Backed by the `value` attribute, which is also what the painted input field writes back on
   * every keystroke - so reading it here always sees what the player typed.
   */
  value: string;
  disabled: boolean;

  /** Null on the outermost element, which has no parent. */
  readonly parentElement: SideloadElement | null;
  readonly children: SideloadElement[];

  /** Null when the attribute is not set on the element. */
  getAttribute(name: string): string | null;
  setAttribute(name: string, value: string): void;
  removeAttribute(name: string): void;
  hasAttribute(name: string): boolean;

  /** Null when nothing on the page matches the selector. */
  querySelector(selector: string): SideloadElement | null;
  querySelectorAll(selector: string): SideloadElement[];
  appendChild(child: SideloadElement): SideloadElement;
  removeChild(child: SideloadElement): SideloadElement;
  insertBefore(child: SideloadElement, reference: SideloadElement): SideloadElement;
  remove(): void;

  /** Drop every child in one go - the cheap way to re-render a list from script. */
  replaceChildren(): void;
  addEventListener(type: string, handler: (event: SideloadEvent) => void): void;
  removeEventListener(type: string, handler: (event: SideloadEvent) => void): void;
  click(): void;
  focus(): void;

  /**
   * Give the keyboard back to the game. A focused field holds the game's typing flag, and while that is up the player
   * cannot move and Escape does nothing - so a page that focuses owes them this.
   */
  blur(): void;

  /**
   * Pin a scrollable box to its end. Takes effect after the next render, which is the only moment it can mean
   * anything: the box a script is looking at is about to be replaced by the one the renderer builds from the DOM it
   * just changed. Without this a chat app shows you the top of the conversation after every message.
   */
  scrollToEnd(): void;

  /**
   * Where this box ended up on screen, in css pixels: `{ x, y, width, height }`, measured from the top left of the
   * viewport - the same frame `position: fixed` is measured in, which is the whole point.
   *
   * A page cannot place anything against another element without this. It is what a browser calls
   * getBoundingClientRect, and its absence is why an "on hover" label had to be laid out INSIDE the row it belonged
   * to, pushing everything along, instead of floating over it like a tooltip.
   *
   * Reflects the LAST render. A box the page has just created has not been laid out yet and reads as zeroes; ask after
   * the render that builds it, not in the handler that asks for it.
   */
  rect(): SideloadRect;
}

/** `element.classList`, the part of it a page actually uses. */
interface SideloadClassList {
  readonly length: number;
  contains(name: string): boolean;
  add(name: string): void;
  remove(name: string): void;
  toggle(name: string): boolean;
}

/** `element.style`. Inline declarations, read and written by property name. */
interface SideloadStyle {
  /**
   * Any CSS property, camelCased, plus `cssText`. WHICH properties actually change anything on screen is a different
   * question and this file does not answer it - the corpus gate does (Workspace/Tests/Sideload.Tests, --corpus).
   */
  [property: string]: string;
}

/** The object handed to a listener. */
interface SideloadEvent {
  readonly type: string;
  readonly target: SideloadElement;
  readonly currentTarget: SideloadElement;

  /** Current text of the control the event came from, for `input` and `keydown`. */
  readonly value: string;

  /**
   * The key for a `keydown`, spelled as the DOM spells it - "Enter", "Tab", "ArrowUp", "r". Empty for other events.
   */
  readonly key: string;

  /**
   * Modifier state on a `keydown`. Always false for other events, and always false for Enter, which comes from the
   * field's own submit and carries no modifier information.
   */
  readonly ctrlKey: boolean;
  readonly shiftKey: boolean;
  readonly altKey: boolean;

  /**
   * True when a `keydown` is the player holding the key rather than pressing it. A page that must act once per press -
   * accepting a completion, submitting - checks this and returns early.
   */
  readonly repeat: boolean;

  /**
   * Whether the field had text selected when the key was pressed.
   *
   * Here because the field acts on some of the same keys the page claimed, and for one of them both meanings are right
   * depending on this: Ctrl+C copies a selection and interrupts when there is none, which is what every terminal on
   * Windows does. A page that claims Ctrl+C without checking this takes copy away.
   */
  readonly hasSelection: boolean;

  /**
   * What raised the event, where more than one thing can: "rightClick" or "escape" for `back`. Empty otherwise. Most
   * pages should treat every source alike; it is here for the ones that must not.
   */
  readonly source: string;

  /**
   * Where inside the clicked element the pointer landed, in CSS pixels from its top-left corner. Zero for events that
   * have no position (`back`, `input`, `keydown`, `orientationchange`).
   *
   * This is what lets a page answer "where did they point at", which a map needs and a plain button does not.
   */
  readonly offsetX: number;
  readonly offsetY: number;

  /**
   * The same point as a 0..1 fraction of the element's own width and height - what you want when the element stands
   * for something with its own coordinate space, like a map.
   */
  readonly normX: number;
  readonly normY: number;

  /**
   * How far the pointer moved since the previous event, in CSS pixels. Set on `drag`; zero on `dragstart` and
   * `dragend`, which mark the ends of a gesture rather than a movement within it.
   *
   * Measured against the page rather than the element, so an element that is being moved BY the drag still reports the
   * movement of the hand rather than the movement of itself.
   */
  readonly deltaX: number;
  readonly deltaY: number;

  /** One wheel notch on a `wheel` event, positive downwards - the sign the DOM uses. */
  readonly wheelDelta: number;
  readonly defaultPrevented: boolean;
  preventDefault(): void;
  stopPropagation(): void;
}

/** A laid-out box in css pixels, measured from the top left of the viewport. */
interface SideloadRect {
  x: number;
  y: number;
  width: number;
  height: number;
}

/** The `s1` global: everything a page can reach outside its own document. */
interface SideloadBridge {
  /** `s1.storage` - a small JSON key/value store per app. */
  readonly storage: SideloadStorage;

  /** The id the app was registered under. Handy for logging and for storage keys a mod also reads. */
  readonly appId: string;

  /**
   * `s1.call(name, arg)` - ask the mod something and get its answer, synchronously.
   *
   * THE SCRIPT'S TIME BUDGET DOES NOT COVER THE MOD'S WORK. A handler may run for 250 ms (ScriptHost.Budget) and that
   * limit is there to catch a runaway script, which this is not: the page is blocked waiting on C# it does not
   * control, and killing it for the mod being slow punishes the wrong side. It reads as a page fault -
   * "s1.on('changed') handler failed: The operation has timed out" - on a page whose own work took a millisecond.
   *
   * So the clock is restarted once the mod answers. What still bounds a genuine runaway is MaxStatements, which a loop
   * calling this a million times reaches on its own.
   */
  call(name: string, argument?: string): string;
  on(name: string, handler: (payload: string) => void): void;
  log(...args: unknown[]): void;

  /**
   * `s1.orientation` - "portrait" or "landscape". Reads the app's setting rather than the measured viewport, so it
   * answers the same during the rotation animation as after it.
   */
  readonly orientation: string;

  /**
   * `s1.setOrientation(v)` - turn the phone. The page keeps its document and its script; only the viewport and the
   * cascade change, so `@media (orientation: ...)` is what decides what the app looks like afterwards.
   */
  setOrientation(orientation: string): void;
}

/** `s1.storage`, a small string key/value store per app. */
interface SideloadStorage {
  get(key: string, fallback?: string): string;
  set(key: string, value: string): void;
  remove(key: string): void;
  clear(): void;
}

/** The `console` global. Everything lands in the MelonLoader log, prefixed with the app id. */
interface SideloadConsole {
  log(...args: unknown[]): void;
  info(...args: unknown[]): void;
  warn(...args: unknown[]): void;
  error(...args: unknown[]): void;
}

/** The `init` argument to `fetch`. Anything a browser accepts beyond these is ignored, not rejected. */
interface SideloadFetchInit {
  method?: string;
  headers?: Record<string, string>;
  body?: string;
  /** Per-call timeout in milliseconds. */
  timeout?: number;
}

/** `response.headers`. Lower-cased names, and a miss is null rather than an empty string. */
interface SideloadResponseHeaders {
  get(name: string): string | null;
  has(name: string): boolean;
}

/**
 * What a `fetch` promise resolves to. The body has already been read by the time the page sees this, so `text()`
 * and `json()` hand back promises that are settled from the start.
 */
interface SideloadResponse {
  readonly ok: boolean;
  readonly status: number;
  readonly statusText: string;
  readonly url: string;
  readonly redirected: boolean;
  readonly headers: SideloadResponseHeaders;
  text(): Promise<string>;
  json(): Promise<unknown>;
}

// The globals, straight off ScriptHost.Bind(). A name that is not on this list does not exist on the page.
declare const document: SideloadDocument;
declare const s1: SideloadBridge;
declare const console: SideloadConsole;
declare function fetch(url: string, init?: SideloadFetchInit): Promise<SideloadResponse>;
declare function setTimeout(fn: () => void, ms: number): number;
declare function setInterval(fn: () => void, ms: number): number;
declare function clearTimeout(id: number): void;
declare function clearInterval(id: number): void;
